# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

  container: ubuntu:16.04

steps:
# - task: AzureResourceManagerTemplateDeployment@3
#deployment of the log Analytic worskpace
  # inputs:
    # deploymentScope: 'Resource Group'
    # azureResourceManagerConnection: 'Conexion_k8s'
    # subscriptionId: '714f1d31-e6fc-4955-acef-4e261636a95e'
    # action: 'Create Or Update Resource Group'
    # resourceGroupName: 'workspacek8bonita'
    # location: 'East US 2'
    # templateLocation: 'Linked artifact'
    # csmFile: './k8loganalytics/workspace-template.json'
    #csmParametersFile: './k8loganalytics/workspace-parameters.json'
    # deploymentMode: 'Incremental'

#- task: AzureCLI@2
 # inputs:
  #  azureSubscription: 'Conexion_k8s'
   # scriptType: 'bash'
    #scriptLocation: 'inlineScript'
    #inlineScript: |
     # az account set -s "Heloise Visual Studio" 
      #az ad app create --display-name k8prueba --homepage "http://localhost/k8prueba"
    # useGlobalConfig: true


- task: AzureResourceManagerTemplateDeployment@3
#deployment of the VNET for CNI network mapping on the pods
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Conexion_k8s'
    subscriptionId: '714f1d31-e6fc-4955-acef-4e261636a95e'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'zmxs1zu2rsgvnet001'
    location: 'East US 2'
    templateLocation: 'Linked artifact'
    csmFile: './k8vnet/vnet-template.json'
    csmParametersFile: './k8vnet/vnet-parameters.json'
    deploymentMode: 'Incremental'

- task: AzureCLI@2
   inputs:
    azureSubscription: 'Conexion_k8s'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az role assignment create --assignee 8cfd2099-7fc0-49f9-9417-71279a532ad2 --role "contributor" --scope /subscriptions/714f1d31-e6fc-4955-acef-4e261636a95e/resourceGroups/zmxs1zu2rsgvnet001/providers/Microsoft.Network/virtualNetworks/Vnetk8
    useGlobalConfig: true

- task: AzureResourceManagerTemplateDeployment@3
#deployment of the k8 cluster
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Conexion_k8s'
    subscriptionId: '714f1d31-e6fc-4955-acef-4e261636a95e'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'zmxs1zu2rsgbonitacrit001'
    location: 'East US 2'
    templateLocation: 'Linked artifact'
    csmFile: './K8/k8-template.json'
    csmParametersFile: './K8/k8-parametersFile.json'
    deploymentMode: 'Incremental'